sudo: required
language: go

go:
  - 1.12
  - 1.13

before_install:
  - cd hwloc
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - ldconfig /usr/local/lib
  - cd ..

script:
  - go test ./...
