sudo: required
dist: trusty
language: go

go:
    - 1.11
    - 1.12

install:
   - true

before_script:

script:
   - cd ${TRAVIS_BUILD_DIR}
   - cd hwloc
   - ./autogen.sh
   - ./configure
   - make
   - sudo make install
   - cd ../
   - make
   - hack/verify-gofmt.sh
